root:
  chain-name: chapel
  rpc-url: https://data-seed-prebsc-1-s1.binance.org:8545/
  relay-hub-address: 0x6239581190D92C570F0a0EfC21dbEF23Dec835c0
  chain-id: 97
  confirmations: 15
  gas-limit: 10000000
  epoch-blocks: 200

child:
  chain-name: bas-dev-01
  rpc-url: https://rpc.dev-01.bas.ankr.com
  relay-hub-address: 0x415B281E2D73D4A8C7151c9159FcDD2046CA63d3
  confirmations: 15
  chain-id: 14000
  epoch-blocks: 1200
  gas-limit: 10000000

relayer:
  private-key: 40b98b34b4796aaf2315baf772d7cdcf2d5eafe6fe11ee751ebd40853874b30b
  grpc-address: 0.0.0.0:6565